name: dyna
description: A widget that provides reactive ColorSchemes based on given source/seed color.
version: 0.0.1-beta.1
homepage: https://github.com/sonicwaste/dyna

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.1.2
  dynamic_color: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
